arch: ResNet50
aug: true
batch_size: 16
ckpt: ''
color_dist_s: 1.0
config_file: null
data: faceforensics
dist: dp
dist_address: 'localhost:1112'
eval_freq: 110
gpu: 0
iters: 5500
log_freq: 55
lr: 0.6
lr_schedule: warmup-anneal
multiplier: 2
name: 'ff-full-contrastive-test-new-aug2'
node_rank: 0
opt: lars
problem: sim-clr
root: '/mnt/results'
save_freq: 110
scale_lower: 0.08
seed: 42
sync_bn: true
temperature: 0.5
tmp: false
verbose: true
warmup: 0.1
weight_decay: 1.0e-06
workers: 2
world_size: 1
pretrained: True