arch: ResNet50
aug: true
batch_size: 256
ckpt: ''
color_dist_s: 1.0
config_file: ''
data: faceforensics
dist: ddp
dist_address: 'localhost'
eval_freq: 330
gpu: 0
iters: 11000
log_freq: 110
lr: 0.3
lr_schedule: warmup-anneal
multiplier: 2
name: 'ff-full-contrastive'
node_rank: 0
opt: lars
problem: sim-clr
root: '/mnt/results'
save_freq: 220
scale_lower: 0.08
seed: 42
sync_bn: true
temperature: 0.5
tmp: false
verbose: true
warmup: 0.1
weight_decay: 1.0e-06
workers: 8
world_size: 1
deepfakes: false
new_transforms: False