arch: ResNet50
aug: true
batch_size: 32
ckpt: ''
color_dist_s: 1.0
config_file: ''
data: faceforensics
dist: ddp
dist_address: 'localhost'
eval_freq: 50040
gpu: 0
iters: 11500
log_freq: 100
lr: 0.6
lr_schedule: warmup-anneal
multiplier: 2
name: 'ff-full-contrastive'
node_rank: 0
opt: lars
problem: sim-clr
root: '/mnt/results'
save_freq: 12510
scale_lower: 0.08
seed: -1
sync_bn: true
temperature: 0.5
tmp: false
verbose: true
warmup: 0.1
weight_decay: 1.0e-06
workers: 8
world_size: 1
